language: cpp
os:
- linux
branches:
  except:
  - gh_pages
  - master
dist: trusty
addons:
  apt:
    packages:
    - docker
notifications:
  email:
    on_success: change
    on_failure: change
git:
  depth: 15
script:
- "./build.sh"
- chmod +x wxmaxima-x86_64.AppImage
deploy:
  provider: releases
  api_key:
    secure: b01O/59en6dQ13ibIUKk9oEu48Lypv2o8XwPl1whKn3XcqJyvrTRYSjBByagATTyswcyB3F6BJs0kYxeVP1WQPsWfZZeXCfhaXu3T/cwwBr81b9eT5eBPU2s8uTurPepfFA5+1OP79UStSKF/Lj8CzCdu13qc0LTNaTPyzxrcD71RuY+4LI8ayZhyq+nqtZKMe+Bzq2PSBE5zYWoS/OdaBOuHucdRClfi0FKu/UDWiyCQQ6kczVpysBZw3Sfaw9NI0V5aaCfUK8Zj2xHwDnSFBk9yuPPYR+EKPTvIbDBoK+JSTJG87gIYP+4O/Hk9jjNS5IxFn3z7jUh03XLInl2C0Aj/TKKmDZao1ovrJhhIPpxYG44zvBmAvZQBYcaWZOkAl8rNAiNXA8RxfgR22E130WDzXnq5ZBqzCevjWuFhPv8BSiU6aB1x3xBdvDWRA4Itqq7RBKam7exM8LDvTRviFPOfl2PFUAv4qOCDVcjDb+m4fimfdK3VsSStdtIROthlIVzEZvCKjwS3mGmj1mYQvLbLsKNmOdSooZTHj5+p/a57LAi9ddAZkv/DTx2+3aw84xmOgY51EJW7cK4OTFp2Y020wQhNKrTVCsFUYONIkZpoIbi2AnX+aDxPfHcJEzlmj7uoAcVJWnmc8oRqmiyTRKgyFd9Uvn80rzj10ddKlo=
  file: wxmaxima-x86_64.AppImage
  on:
    repo: wxMaxima-developers/docker-wxmaxima
    tags: true
