language: cpp
os:
- linux
branches:
  except:
  - gh_pages
  - master
dist: trusty
addons:
  apt:
    packages:
    - docker
notifications:
  email:
    on_success: change
    on_failure: change
git:
  depth: 15
script:
- "./build.sh"
- chmod +x wxmaxima-x86_64.AppImage
deploy:
  provider: releases
  edge: true
  draft: false
  file: wxmaxima-x86_64.AppImage
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
  api-key:
    secure: nnI1Cv9QkDJ1M4xqiwC7Mh37QIuNwOGa9N01PFUl8A/J46pFDdpojZJKUe7XijT7c/Bv8yTkru/IWWW/9yGL60mIH57TRtfBR8qAYm5hA05sLELW0uJVTI/uN8DCHmBBpSg19UuDWk8GRuPL06xmAtRueiKkm9M7tifz/l6Gv8tCFu1xj/V9CLmZn56iuNln7jqFyLU984vVrVlZMm/4tKi0GPXP/GW6HT/zRhMej82+9CfBZsj+vk9zN7xNfyFHfErwR1KXdZmXHj3fZN8e+T5p6TCIt/TQuLzYBX1KZmsVXSqdKlgcWKLaIPLj5+J+dCnTtgoCpMJ4Oh38s4EBxX/6Z7bXp3Rhu2niAleHLqHsov+FObC7WklNIMDkg1b5d2WuesdeyKmZz12BSofojAPOCRneykbyEf/zqVzCQNZRSQrZ0zcCbIYypiqBwe8YSXhG3Tjc/M7N1A1FxYrU9Rz8U8bywGmcgAGsNLYerAZEIzuHvL56U460SOi5AP3iy3AH3JRYCRoQp9TRLEPGoLdJztzmY99A24wn7oUPJgV//58HKqlhHTgYFLCylQHhThVJTJzrcMN370rlemrWTdqaE7DVEc3r9vlQuRIS3fzu82HYmDGq9AkRfdcskWAnzFEhPmP0xE9FAd1JfKjvldkWawBpq1yRVq8e6oVVfQA=
