language: cpp
os:
- linux
branches:
  except:
  - gh_pages
dist: trusty
addons:
  apt:
    packages:
    - docker
notifications:
  email:
    on_success: change
    on_failure: change
git:
  depth: 15
script:
- ./build.sh

deploy:
  provider: releases
  edge: true
  file: "wxmaxima-x86_64.AppImage"
  skip_cleanup: true
  token: $TRAVIS_DEPLOY_KEY
  on:
    tags: true