name: compile

on: [push]

jobs:
  compile:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout_git
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 15
    - name: install_packages
      run: |
           sudo apt-get update
           sudo apt-get install runc
           sudo apt-get install containerd
           sudo apt-get install docker.io
    - name: start_docker
      run: |
           sudo gpasswd -a $USER docker
           newgrp docker
    - name: build
      run: |
           sudo "./build.sh"
           sudo chmod a+x wxmaxima-x86_64.AppImage
