name: compile

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  compile:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout_git
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 15
    - name: install_packages
      run: |
           sudo apt-get -q update
           sudo apt-get -q install docker.io
    - name: build
      run: |
           "./build.sh"
           chmod +x wxmaxima-x86_64.AppImage
